/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decryptAes(text: string, key: string): string;

export declare function decryptCezar(text: string, shift: number): string;

export declare function decryptRunningKey(text: string, key: string): string;

export declare function decryptVigenere(text: string, key: string): string;

export declare function encryptAes(text: string, key: string): string;

export declare function encryptCezar(text: string, shift: number): string;

export declare function encryptRunningKey(text: string, key: string): string;

export declare function encryptVigenere(text: string, key: string): string;
