/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decryptAes(text: string, key: string): string

export declare function decryptCezar(text: string, shift: number): string

export declare function decryptRunningKey(text: string, key: string): string

export declare function decryptVigenere(text: string, key: string): string

export declare function encryptAes(text: string, key: string): string

export declare function encryptCezar(text: string, shift: number): string

export declare function encryptRunningKey(text: string, key: string): string

export declare function encryptVigenere(text: string, key: string): string

export declare function generateRsaKeys(): RsaKeyPair

export declare function rsaDecrypt(cipher: string, n: string, d: string): string

export declare function rsaEncrypt(message: string, n: string, e: string): string

export interface RsaKeyPair {
  n: string
  e: string
  d: string
}
