/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decryptCezar(text: string, shift: number): string

export declare function encryptCezar(text: string, shift: number): string
